# SRC = $(shell find src -type f -name '*.c')
SRC = \
src/helpers.c \
src/env/env_get_set.c \
src/env/env_ptr.c \
src/executable/executable_un_init.c \
src/executable/executable_add_here_doc.c \
src/executable/builtins/builtin_exit.c \
src/executable/builtins/builtin_unset.c \
src/executable/builtins/builtin_pwd.c \
src/executable/builtins/builtin_export.c \
src/executable/builtins/builtin_env.c \
src/executable/builtins/builtin_echo.c \
src/executable/builtins/executable_get_builtin_exec.c \
src/executable/builtins/builtin_cd.c \
src/executable/executable_add_pipe.c \
src/executable/executable_add_fd_redirect.c \
src/executable/executable_init.c \
src/executable/executable_add_arg.c \
src/executable/executable_run.c \
src/utils/working_directory.c \
src/utils/path_utils.c \
src/utils/is_valid_env.c \
src/utils/find_executable.c \
src/command/command_read/destroy.c \
src/command/command_read/expand_environment_variables.c \
src/command/command_read/quoted_text.c \
src/command/command_read/command_read.c \
src/command/command_read/goto_next_split.c \
src/command/handle_invalid_grammar_rule.c \
src/command/run_command_as_executable.c \
src/command/push_execs.c \
src/malloc_wrappers/other.c \
src/malloc_wrappers/list.c \
src/signal/signal_handler.c \
